# Generated by Django 3.1.7 on 2021-03-25 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210325_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_registration',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
