# Generated by Django 3.1.7 on 2021-04-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210325_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
