# Generated by Django 3.1.7 on 2021-03-15 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default='30')),
                ('membership_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=30, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='profiles.userprofile')),
                ('user_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='membership.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=datetime.datetime.today)),
                ('membership_duration', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='membership.membership')),
                ('subcription_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='membership.usermembership')),
            ],
        ),
    ]
