# Generated by Django 3.1.7 on 2021-03-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20210319_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='slug',
        ),
    ]
