# Generated by Django 3.1.7 on 2021-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_membership_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default='30'),
        ),
    ]
