# Generated by Django 3.1.7 on 2021-03-02 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20210302_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
