# Generated by Django 3.1.7 on 2021-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_subscription_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
