# Generated by Django 3.1.7 on 2021-03-03 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210302_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
