# Generated by Django 3.1.7 on 2021-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20210303_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration_days',
            field=models.IntegerField(default='30'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=30, null=True),
        ),
    ]
