# Generated by Django 3.1.7 on 2021-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_subscription_extended_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_for_day',
            field=models.FloatField(default=None),
        ),
    ]
