# Generated by Django 3.1.7 on 2021-03-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20210322_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price_for_day',
        ),
    ]
