# Generated by Django 3.1.7 on 2021-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_subscription_price_for_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_renewal_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='extended_subscription_days',
            field=models.IntegerField(null=True),
        ),
    ]
