# Generated by Django 3.1.7 on 2021-04-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20210322_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subcription_membership',
            new_name='subscription_membership',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='membership_duration',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price_for_day',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='total_renewal_price',
        ),
    ]
