# Generated by Django 3.1.7 on 2021-04-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210409_1843'),
        ('membership', '0013_auto_20210409_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='subscription',
            name='member_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memb', to='profiles.userprofile'),
        ),
    ]
