# Generated by Django 3.1.7 on 2021-04-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210409_1843'),
        ('membership', '0015_remove_subscription_member_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='member_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='user_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to='membership.membership'),
        ),
    ]
