# Generated by Django 3.1.7 on 2021-04-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_auto_20210414_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
