# Generated by Django 3.1.7 on 2021-04-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_auto_20210414_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_membership',
            new_name='user_membership',
        ),
    ]
