# Generated by Django 3.1.7 on 2021-04-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_auto_20210414_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='slug',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_number',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
