# Generated by Django 3.1.7 on 2021-02-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_ordermembership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderMembership',
        ),
    ]
