# Generated by Django 3.1.7 on 2021-02-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210225_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='membership',
        ),
    ]
